logging:
  file:
    path: D:\\boot
  level:
    root: info
    com:
      shangma: debug
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss}) [%c]-[%p] %m%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%c]-[%p] %m%n'

